Update github-actions-demo.yml

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -24,4 +24,10 @@ jobs:
           npm install
           result=$(npm test)
           echo $result
+          if [$result == *PASSED*] ; then
+          echo "🍏 Validated......"
+          elif[result == *Failed*] ; then
+          echo "Validator failed and exiting..."
+          exit 1
+          fi
       - run: echo "🍏 This job's status is ${{ job.status }}."
